### ISSUE TITLE
orientation: landscape | portrait support

### ISSUE THREAD

**Issue by gloddy** [nymag/responsive-filenames#1]

**Comment by nelsonpecora** [comment]
?

**Comment by gloddy** [comment]
Adding support for landscape and portrait as keywords, similar to print.
landscape.css -> @media (orientation: portrait) { ... }
portrait.css -> @media (orientation: landscape) { ... }

**Comment by nelsonpecora** [comment]
ahh. I'm not so sure how useful that is, considering this (from MDN):

> Note: This value does not correspond to actual device orientation. Opening the soft keyboard on most devices in portrait orientation will cause the viewport to become wider than it is tall, thereby causing the browser to use landscape styles instead of portrait.

**Comment by gloddy** [comment]
This situation doesn't mean the keywords are useless.

**Comment by nelsonpecora** [comment]
I say we table this and implement it if we ever find ourselves needing this. I don't think we have a single orientation media query in our codebase currently.

**Comment by gloddy** [comment]
Agreed.
