### ISSUE TITLE
Guarantee that media queries are added at the end

### ISSUE THREAD

**Issue by ughitsaaron** [nymag/responsive-filenames#8]
RFN currently doesn't guarantee that rules inside of media queries are added after rules without media queries, e.g., this can happen:

```
/* 1024+.css */
@media screen and (max-width:1024px) {
  .foo {
    display: block;
  }
}

/* all.css */
.foo {
  display: none;
}
```

This means that `display: none` is rendered at widths 1024px+, but the developer or designer probably wrote the rules expecting .foo to render `display: block`.

Expected behavior would be that rules in media queries are always compiled to be added after rules without media queries, e.g.,

```
/* all.css */
.foo {
  display: none;
}

/* 1024+.css */
@media screen and (max-width:1024px) {
  .foo {
    display: block;
  }
}
```

**Comment by ironspecs** [comment]
+1.  Order matters.

In what cases do they reverse?

Though, ideally, this reliance on order would be removed from the css doing it.  The factory's css relies on order a lot, and it's caused a lot of problems.  Causing specificity wars that rely on ordering is probably bad.

**Comment by nelsonpecora** [comment]
How does this sound:
1. any default css (anything that doesn't match, all.css, etc)
2. media query css (order by alpha)
3. print.css

**Comment by ughitsaaron** [comment]
@yoshokatana :100:
